//
//  MainWorker.swift
//  CleanArchitecture
//
//  Created by imform-mm-2101 on 2021/07/06.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Combine
import SwiftUI

class MainWorker: APIService {
    var session: NetworkService = NetworkService()
    var cancellable: Set<AnyCancellable> = []
    
    func doSomeWork(onComplete: @escaping((TestModel) -> Void),
                    onError: @escaping((Error) -> Void)) {
        test(string: "test")
            .sink { completion in
                switch completion {
                case .failure(let error):
                    onError(error)
                    break
                case .finished:
                    break
                }
            } receiveValue: { data in
                onComplete(data.value)
            }
            .store(in: &cancellable)
    }
}
