//
//  MainPresenter.swift
//  CleanArchitecture
//
//  Created by imform-mm-2101 on 2021/07/06.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentTodos(response: Main.TodoList.Response)
    func presentError(response: Main.TodoList.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    func presentTodos(response: Main.TodoList.Response) {
        let viewModel = Main.TodoList.ViewModel(
            result: response.result,
            error: nil
        )
        viewController?.displayTest(viewModel: viewModel)
    }
    
    func presentError(response: Main.TodoList.Response) {
        viewController?.displayError(
            viewModel: Main.TodoList.ViewModel(result: [], error: response.error)
        )
    }
}
