//
//  MainRouter.swift
//  CleanArchitecture
//
//  Created by imform-mm-2101 on 2021/07/06.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToSomewhere()
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    // MARK: Routing
    func routeToSomewhere() {
        let destinationVC = LoginViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToLogin(source: self.dataStore!, destination: &destinationDS)
        destinationVC.modalTransitionStyle = .flipHorizontal
        destinationVC.modalPresentationStyle = .fullScreen
        self.viewController?.present(destinationVC, animated: true, completion: nil)
    }
    
    // MARK: Passing data
    func passDataToLogin(source: MainDataStore, destination: inout LoginDataStore) {
        destination.todos = source.todos
    }
}
