//
//  ListInteractor.swift
//  CleanArchitecture
//
//  Created by imform-mm-2101 on 2021/07/06.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBusinessLogic {
    func doSomething(request: List.Something.Request)
}

protocol ListDataStore {
    var todos: [TestModel] { get set }
}

class ListInteractor: ListBusinessLogic, ListDataStore {
    var presenter: ListPresentationLogic?
    var worker: ListWorker?
    var todos: [TestModel] = []
    
    // MARK: Do something
    func doSomething(request: List.Something.Request) {
        worker = ListWorker()
        worker?.doSomeWork()
        
        let response = List.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
